### ISSUE TITLE
Works randomly on my side

### ISSUE THREAD

**Issue by SunSea88** [burakgarci/auto-dim-twitter#1]
Hello,

I would like to know how to set the script for 24 hours a day please ?

In addition on my side, it works randomly from 19 to 8 😔

Thank you for your answer.

Google Chrome Browser with Tampermonkey

**Comment by burakgarci** [comment]
Hello!

It is late, but I think it is better to update for future reference.

I believe I've answered your feedback on [Greasy Fork](https://greasyfork.org/en/scripts/433450-auto-dim-twitter/discussions/211713)

To use the Dim theme for 24 hours, you do not need a script; just go to the settings in your Twitter web app and change the preferred theme.
